version: "3"
services:
  #Nginx service
  ngnix:
      build: ./nginx
      depends_on:
        - api
        - client
      ports:
        - "8080.80"
  #postgress database
  postgress_db:
      image: "postgres"
      environment:
          - POSTGRES_PASSWORD=postgres_password
  # Redis database
  redis_db:
      image:  "redis"
  # API Service
  api:
      build: ./server
      image: "fdk1/complex_api"
      environment:
          - REDIS_HOST=redis_db
          - REDIS_PORT=3679
          - PGHOST=postgres_db
          - PGPORT=5432
          - PGUSER=postgres
          - PGPASSWORD=postgres_password
          - PGDATABASE=postgres  

  # Worker service
  worker:
      build: ./server
      image: "fdk1/complex_worker"
      environment:
          - REDIS_HOST=redis_db
          - REDIS_PORT=6379
  # Frontend
  client:
      build: ./client
      image: "fdk1/complex_client"  
